### ISSUE TITLE
fix merge conflict

### ISSUE THREAD

**Issue by otanim** [iteratehackerspace/cheatsheet#23]
https://github.com/otanim/cheatsheet/blob/master/git/README.md file contains conflicts with the previous version.

It should be fixed.

**Comment by fxfactorial** [comment]
Ah, now I see why you didn't fix it. 

Yea, accidentally a Merge conflict was accepted =/

**Comment by otanim** [comment]
exactly

**Comment by fxfactorial** [comment]
Painful merge, just picked yours
