### ISSUE TITLE
merge of different versions of git

### ISSUE THREAD

**Issue by otanim** [iteratehackerspace/cheatsheet#24]
As I have other version of git's cheatsheet, I've decided to create a new folder.

files of folders: **git/** and **git-version-of-otanim/** should be merged.

**Comment by fxfactorial** [comment]
Yea I was wondering why you didn't just do it? 

Please go for it, also apparently a mistake on the git push description

**Comment by otanim** [comment]
refer to: https://github.com/iteratehackerspace/cheatsheet/issues/23
