### ISSUE TITLE
Acknowledgements

### ISSUE THREAD

**Issue by fxfactorial** [iteratehackerspace/cheatsheet#27]
We shouldn't have multiple subdirectories of topics, aka no edgar's version of git, etc etc. 

We should add an acknowledgement section at the bottom of the root README

**Comment by otanim** [comment]
@fxfactorial I've created different version of the same topic, because of merge issues, I agree that there is no need to make different versions.
refer https://github.com/iteratehackerspace/cheatsheet/issues/24

**Comment by fxfactorial** [comment]
I'm cleaning it up now
