### ISSUE TITLE
fix the documentation

### ISSUE THREAD

**Issue by otanim** [iteratehackerspace/cheatsheet#70]
Well guys :)
With great power comes great responsibility.

Please:
- do not ruin the existing doc.
- create a pull requests for each changes.
- do not do direct pushes to the master branch.  

If you are trying to advertise yourself do it nicely :)

screenshot attached:
![image](https://cloud.githubusercontent.com/assets/7108843/23676996/e4e0e788-0397-11e7-967b-38aec0133d6d.png)

**Comment by paerallax** [comment]
@otanim, care to elaborate?

**Comment by otanim** [comment]
@paerallax in general I'm talking about this commits:
- 7836d4d69fc224242b518911460a2b60b2c3a512
- 2668464050a9b5d33cf00db4000dde92be5b8909

How are you guys keep managing changes ?
Can anyone describe why do we don't need «օգտակար հղումներ» section, is it that much useless, that after accepting my pull request of "useful links" section, someone removed it without any reason ?

@fxfactorial FYI

**Comment by fxfactorial** [comment]
The pull requests definitely need to be tightened up, you're right. I'm at a disadvantage insofar as I can't read all of it, just parts.

Of course we can use git blame to check who made the mistake, but let's look instead towards better PR management. 

As the repo has become non trivial and used by many beginners, the burden of making sure everything is correct goes up. 

We will improve, thank you for pointing this out Arman.

**Comment by paerallax** [comment]
What's wrong with https://github.com/iteratehackerspace/cheatsheet/commit/7836d4d69fc224242b518911460a2b60b2c3a512?

As for https://github.com/iteratehackerspace/cheatsheet/commit/2668464050a9b5d33cf00db4000dde92be5b8909, @narghev may be able to explain furhter.

**Comment by otanim** [comment]
@fxfactorial glad to know.
@paerallax I kindly suggest you to go to the commit page, then click on View button:
![image](https://cloud.githubusercontent.com/assets/7108843/23697674/1112ddf6-0402-11e7-9666-003f5fcabec0.png)
then you should be able to see the rendered content itself.

Btw. I've created screenshots of typos, if it's still not clear where was the typo:
![image](https://cloud.githubusercontent.com/assets/7108843/23697945/1eba2080-0403-11e7-83e5-47a487dad794.png)
==========================
![image](https://cloud.githubusercontent.com/assets/7108843/23698181/03ff22b2-0404-11e7-93dd-46433aaa0e6c.png)

Does it make sense ?

**Comment by paerallax** [comment]
Dear @otanim, thank you for the detailed explanation on GitHub usage but I'm well aware of it :) 
I don't see a typo in the first example. Regarding the second, as far as I know, it was deleted due to wrong placement. We should not pollute the main README.md with that type of material. That belongs to a separate directory named useful-links or something in that matter. 
Now, I should note that I don't have access to master branch and I'm also curious to know why something was deleted without providing an explanation, so to get this straight, I'll mention @narghev again so he clarifies everything.

**Comment by narghev** [comment]
Dear @otanim, so in Iterate hackerspace we have decided to keep the main readme as clean as possible, by saying clean i dont mean without typos (typos can and will always happen). So if you want to add stuff that is not mentioned in the main readme, you can add them in other readmes, and subfolders, sorry for not clarifying earlier

**Comment by otanim** [comment]
Well, I see your point. I wish you good luck :+1:

**Comment by fxfactorial** [comment]
@otanim No need to be salty about it, some misunderstandings and bad commits. Never attribute to malice what you can attribute to accident. 

Arman, you are a big reason for this repos success and I hope continued success. I split out the acknowledgments as a file, please add your name there. Every open source project at least acknowledges the people, like you, who put in the hours of free work to improve the collective. In our case its the Armenian tech mind, an incredible and worthy goal. 

I also split out the more useful info part as its useful, I'd like to see that expanded as well.
